In [1]:
from kaggle_environments import make
from kaggle_environments.envs.halite.helpers import *

from main import HaliteManager
from base import *
from nets import ShipStateNet, ShipDepositNet
import numpy as np
import keras
import re
import os
import json
from functools import reduce

In [2]:
with open('data/populations/pop0.json', 'r') as f:
    W = json.load(f)
    W = W['deposit_manager']
    print([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])
    print(np.mean([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W]))

[0.04072730804211425, 0.046423854073509574, 0.03900334175335729, 0.04408993403194472, 0.040536260639419196, 0.03876971025019884]
0.04159173479842398


In [3]:
with open('data/populations/pop1.json', 'r') as f:
    W = json.load(f)
    W = W['deposit_manager']
    print([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])
    print(np.mean([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W]))

[0.07369022109809686, 0.038762862255680375, 0.06005321038204436, 0.08248467808251107, 0.04688424000161269, 0.047536595910787585]
0.05823530128845549


In [6]:
with open('data/populations/pop19.json', 'r') as f:
    W = json.load(f)
    W = W['deposit_manager']
    print([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])
    print(np.mean([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W]))

[0.27586794650034674, 0.35004795893757384, 0.2681082921986089, 0.37903965019694064, 0.36047418029758166, 0.5063525121773143]
0.35664842338472774


In [ ]:
with open('data/populations/pop32.json', 'r') as f:
    W = json.load(f)
    W = W['deposit_manager']
    print([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])
    print(np.mean([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W]))

In [ ]:
with open('data/populations/pop36.json', 'r') as f:
    W = json.load(f)
    W = W['deposit_manager']
    print([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])
    print(np.mean([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W]))

In [ ]:
with open('data/populations/pop37.json', 'r') as f:
    W = json.load(f)
    W = W['deposit_manager']
    print([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])
    print(np.mean([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W]))
    print([np.sum(np.array(w)) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])

In [ ]:
with open('data/populations/pop42.json', 'r') as f:
    W = json.load(f)
    W = W['deposit_manager']
    print([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])
    print(np.mean([np.sum(np.abs(np.array(w))) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W]))
    print([np.sum(np.array(w)) / reduce(lambda a, b: a*b, np.array(w).shape)  for w in W])

In [2]:
shipyard_manager = BaseShipyardManager()
ship_state_manager = BaseShipStateManager()
attack_manager = BaseAttackManager()
collect_manager = BaseCollectManager()
convert_manager = BaseConvertManager()
deposit_manager = BaseDepositManager()

manager = HaliteManager(
    shipyard_manager=shipyard_manager,
    ship_state_manager=ship_state_manager,
    attack_manager=attack_manager,
    collect_manager=collect_manager,
    convert_manager=convert_manager,
    deposit_manager=deposit_manager,
)

In [3]:
shipyard_manager = BaseShipyardManager()
attack_manager = BaseAttackManager()
collect_manager = BaseCollectManager()
convert_manager = BaseConvertManager()

net_deposit_manager = ShipDepositNet(5)
net_ship_state_manager = ShipStateNet(5)

net_manager = HaliteManager(
    shipyard_manager=shipyard_manager,
    ship_state_manager=ship_state_manager,
    attack_manager=attack_manager,
    collect_manager=collect_manager,
    convert_manager=convert_manager,
    deposit_manager=net_deposit_manager,
)

In [9]:
net_manager.load_w('data/populations/pop19.json') 

In [ ]:
environment.render(mode="ipython", width=800, height=600)

In [5]:
environment = make("halite", configuration={"size": 20, "startingHalite": 1000}, debug=True)
environment.run([
    lambda x, y: net_manager.agent(x, y),
    lambda x, y: manager.agent(x, y),
    lambda x, y: manager.agent(x, y), 
    lambda x, y: manager.agent(x, y)
])

ship_owner 3
ship_owner 1
shipyard_owner 3
shipyard_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 3
ship_owner 1
shipyard_owner 3
shipyard_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 3
ship_owner 1
shipyard_owner 3
shipyard_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
ship_owner 4
shipyard_owner 4
ship_owner 2
shipyard_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
ship_owner 4
shipyard_owner 4
ship_owner 2
shipyard_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
shipyard_owner 3
shipyard_owner 1
ship_o

ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 4
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 1
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 1
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 1
shipyard_owner 3
shipyard_owner 1
ship_owner 3
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 1
shipyard_owner 3
shipyard_owner 1
ship_owner 3
ship_owner 4
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 1
ship_owner 1
shipyard_owner 3
shipyard_owner 1
ship_owner 3
shipyard_owner 4
ship_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 1
ship_owner 3
shipyard_owner 3
shipyard_owner 1
shipyard_owner 4
ship_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 1
ship_owner 3
shipyard_owner

ship_owner 3
ship_owner 1
shipyard_owner 3
shipyard_owner 1
shipyard_owner 4
ship_owner 2
shipyard_owner 2
ship_owner 4
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 4
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 4
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 4
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 2
ship_owner 4
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 4
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 4
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_owner 1
ship_owner 1
shipyard_owner 4
shipyard_owner 2
ship_owner 4
ship_owner 2
ship_owner 3
shipyard_owner 3
shipyard_o

[[{'action': {},
   'reward': 5000,
   'info': {},
   'observation': {'player': 0,
    'step': 0,
    'halite': [0,
     0,
     5,
     0,
     0,
     3,
     0,
     0,
     10,
     4,
     4,
     10,
     0,
     0,
     3,
     0,
     0,
     5,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     12,
     10,
     0,
     0,
     0,
     0,
     10,
     12,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     2,
     1,
     0,
     0,
     10,
     11,
     11,
     10,
     0,
     0,
     1,
     2,
     0,
     0,
     0,
     0,
     0,
     7,
     0,
     0,
     6,
     3,
     4,
     0,
     0,
     6,
     6,
     0,
     0,
     4,
     3,
     6,
     0,
     0,
     7,
     0,
     0,
     0,
     8,
     2,
     8,
     0,
     0,
     0,
     6,
     1,
     1,
     6,
     0,
     0,
     0,
     8,
     2,
     8,
     0,
     0,
     0,
     0,
     4,
     0,
     3,
     0,
     1,
     0,
     0,
     0,
  

In [ ]:
from collections import Counter

In [ ]:
with open('data/base/x.json', 'r') as f:
    x = json.load(f)

In [ ]:
with open('data/base/y.json', 'r') as f:
    y = json.load(f)

In [ ]:
X = np.array([xi[0] for xi in x])

In [ ]:
net = Net(5)
net.train(X, y, 200)
np.mean(np.argmax(net.model.predict(X), axis=1) == y)

In [ ]:
net.play(20)

In [ ]:
p = np.random.random(len(y)) < 0.2
yy = y*p + np.random.choice(list(range(7)), len(y)) * (1-p)
(y == yy).mean()

In [ ]:
from kaggle_environments import make
from kaggle_environments.envs.halite.helpers import *

# Create a test environment for use later
board_size = 20
environment = make("halite", configuration={"size": board_size, "startingHalite": 1000})
agent_count = 4
environment.reset(agent_count)
state = environment.state[0]

In [ ]:
board = Board(state.observation, environment.configuration)
print(board)

In [ ]:
from extra import *

In [ ]:
get_npboard_part_by_point(all_board_params(board)[1], (5, 14), 5)

In [ ]:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [ ]:
all_board_params(board)

In [ ]:
net.model.predict(X[0].reshape(1, 127))

In [ ]:
net.mode

In [ ]:
y

In [ ]:
filenames = [f for f in os.listdir('data/populations/') if f.endswith('.json')]
filepop = [int(re.findall('(\d)+', f)[0]) for f in filenames]
net_dict = {}
file_dict = dict(zip(filepop, filenames))
for num, file in file_dict.items():
    net = Net(5)
    net.load_w('data/populations/' + file)
    net_dict[num] = net

In [ ]:
file_dict

In [ ]:
net_dict[4].play(20)

In [ ]:
s_nets = sorted(nets, key=lambda network: network.score, reverse=True)
print('   ', s_nets[0].score, s_nets[0].wins)
print('   ', s_nets[24].score, s_nets[24].wins)
print('   ', s_nets[49].score, s_nets[49].wins)

In [ ]:
print('   ', s_nets[5]._acts)
s_nets[5].play(20)

In [ ]:
print('   ', s_nets[24]._acts)
s_nets[24].play(20)

In [ ]:
print('   ', s_nets[49]._acts)
s_nets[49].play(20)

In [ ]:
net = Net()
model = net.model

In [ ]:
model.compile(
    optimizer=keras.optimizers.RMSprop(learning_rate=0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
)

In [ ]:
model.fit(np.matrix(X_train), np.random.choice(list(range(5)), len(X_train)), epochs=20, verbose=False)

In [ ]:
environment.run([agent(model), "random", "random", "random"])
res = [x[0] for x in environment.__dict__['steps'][-1][0]['observation']['players']] 
print('   ', res[0] - max(res[1:]))
environment.render(mode="ipython", width=800, height=600)

In [ ]:
environment.__dict__['steps']

In [ ]:
evaluate(environment)

In [ ]:
for i in range

In [ ]:
model.weights[0]

In [ ]:
w[0]